### ISSUE TITLE
audio module: Snowboy support?

### ISSUE THREAD

**Issue by n8atnite** [180D-FW-2020/Team8#18]
Snowboy is an offline hotword recognizer for specific keywords. The speech recognition library that the audio module is built on has support for it.

https://snowboy.kitt.ai/

From the speech_recognition library: "The snowboy_configuration parameter allows integration with Snowboy, an offline, high-accuracy, power-efficient hotword recognition engine. When used, this function will pause until Snowboy detects a hotword, after which it will unpause. This parameter should either be None to turn off Snowboy support, or a tuple of the form (SNOWBOY_LOCATION, LIST_OF_HOT_WORD_FILES), where SNOWBOY_LOCATION is the path to the Snowboy root directory, and LIST_OF_HOT_WORD_FILES is a list of paths to Snowboy hotword configuration files (*.pmdl or *.umdl format)."

**Comment by nzani** [comment]
First of all, their advertisement is amazing. Second, looks good to me, certainly better than anything I could implement. What key words were you thinking of using?

**Comment by thomaskost17** [comment]
ya know theyre right, i dont want to write my own clunky speech recognition software.  Personally a fan of just using "hey meat"

**Comment by n8atnite** [comment]
> First of all, their advertisement is amazing. Second, looks good to me, certainly better than anything I could implement. What key words were you thinking of using?

not sure, maybe decided at runtime.

**Comment by n8atnite** [comment]
rejected, we have built up our own framework anyway
