### ISSUE TITLE
ModuleNotFoundError for pocketsphinx

### ISSUE THREAD

**Issue by n8atnite** [180D-FW-2020/Team8#7]
I had a lot of trouble with getting pocketsphinx to be found in sys.path.
If you encounter this error, try running `pip3 install pocketsphinx` after having installed pocketsphinx and sphinxbase from conda-forge channel thru conda.

The environment.yml file in my audio branch should take care of this. If not, post error and config here.

**Comment by thomaskost17** [comment]
this was discussed in the meeting but will put here for completeness as it was a fairly painless process:

1.  create conda environment with desired python version
```
conda create --name <audio_environement_name> python=3.6
conda activate <audio_environement_name>
```
2. Install the necessary dependencies:
```
sudo apt-get install portaudio19-dev python-all-dev python3-all-dev && python -m pip install pyaudio
python -m pip install --upgrade pip setuptools wheel
python -m pip install --upgrade pocketsphinx
python -m pip install SpeechRecognition
```

This should give an environment that has all dependencies properly installed and a python version that is compatible with the libraries.
